# Generated by Django 4.1.7 on 2023-04-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=500)),
                ('color', models.CharField(max_length=500)),
                ('region', models.CharField(max_length=500)),
                ('month', models.CharField(max_length=500)),
                ('prediction', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=500)),
                ('month', models.CharField(max_length=500)),
                ('sales', models.IntegerField()),
                ('color', models.CharField(max_length=500)),
                ('region', models.TextField(max_length=500)),
                ('date', models.CharField(max_length=500)),
            ],
        ),
    ]
